CRITICAL - 2024-03-20 01:57:04 --> CodeIgniter\Exceptions\FrameworkException: The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 252.
 1 SYSTEMPATH\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 ROOTPATH\spark(88): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2024-03-20 01:57:05 --> ErrorException: Uncaught Error: Class "Locale" not found in C:\xampp\htdocs\wbs-ci\system\I18n\TimeTrait.php:74
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\I18n\TimeTrait.php(115): CodeIgniter\I18n\Time->__construct(NULL, NULL, NULL)
#1 C:\xampp\htdocs\wbs-ci\system\HTTP\ResponseTrait.php(468): CodeIgniter\I18n\Time::now()
#2 C:\xampp\htdocs\wbs-ci\system\HTTP\ResponseTrait.php(446): CodeIgniter\HTTP\Response->sendHeaders()
#3 C:\xampp\htdocs\wbs-ci\system\Debug\ExceptionHandler.php(81): CodeIgniter\HTTP\Response->send()
#4 C:\xampp\htdocs\wbs-ci\system\Debug\Exceptions.php(156): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#6 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(252): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(214): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 C:\xampp\htdocs\wbs-ci\spark(88): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\I18n\TimeTrait.php on line 74.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-03-20 02:09:52 --> ParseError: syntax error, unexpected token "return"
in APPPATH\Controllers\HomeController.php on line 16.
 1 SYSTEMPATH\Autoloader\Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\wbs-ci\\app\\Controllers\\HomeController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\HomeController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\HomeController')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\HomeController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:20:45 --> ParseError: syntax error, unexpected token "return"
in APPPATH\Controllers\HomeController.php on line 16.
 1 SYSTEMPATH\Autoloader\Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\wbs-ci\\app\\Controllers\\HomeController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\HomeController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\HomeController')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\HomeController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:21:14 --> ParseError: syntax error, unexpected token "return"
in APPPATH\Controllers\HomeController.php on line 16.
 1 SYSTEMPATH\Autoloader\Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\wbs-ci\\app\\Controllers\\HomeController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\HomeController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\HomeController')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\HomeController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:21:15 --> ParseError: syntax error, unexpected token "return"
in APPPATH\Controllers\HomeController.php on line 16.
 1 SYSTEMPATH\Autoloader\Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\wbs-ci\\app\\Controllers\\HomeController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\HomeController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\HomeController')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\HomeController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:21:16 --> ParseError: syntax error, unexpected token "return"
in APPPATH\Controllers\HomeController.php on line 16.
 1 SYSTEMPATH\Autoloader\Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\wbs-ci\\app\\Controllers\\HomeController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\HomeController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\HomeController')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\HomeController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:21:16 --> ParseError: syntax error, unexpected token "return"
in APPPATH\Controllers\HomeController.php on line 16.
 1 SYSTEMPATH\Autoloader\Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\wbs-ci\\app\\Controllers\\HomeController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\HomeController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\HomeController')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\HomeController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:21:16 --> ParseError: syntax error, unexpected token "return"
in APPPATH\Controllers\HomeController.php on line 16.
 1 SYSTEMPATH\Autoloader\Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\wbs-ci\\app\\Controllers\\HomeController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\HomeController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\HomeController')
 4 SYSTEMPATH\CodeIgniter.php(899): class_exists('\\App\\Controllers\\HomeController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:37:13 --> Error: Cannot call constructor
in APPPATH\Controllers\LaporController.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\LaporController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:37:49 --> Error: Cannot call constructor
in APPPATH\Controllers\LaporController.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\LaporController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:37:50 --> Error: Cannot call constructor
in APPPATH\Controllers\LaporController.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\LaporController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:37:50 --> Error: Cannot call constructor
in APPPATH\Controllers\LaporController.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\LaporController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:37:50 --> Error: Cannot call constructor
in APPPATH\Controllers\LaporController.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\LaporController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:37:50 --> Error: Cannot call constructor
in APPPATH\Controllers\LaporController.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\LaporController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:39:10 --> Error: Cannot call constructor
in APPPATH\Controllers\LaporController.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\LaporController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:39:30 --> Error: Cannot call constructor
in APPPATH\Controllers\LaporController.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\LaporController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:40:09 --> ParseError: syntax error, unexpected token "(", expecting identifier or variable or "{" or "$"
in APPPATH\Config\Routes.php on line 13.
 1 SYSTEMPATH\CodeIgniter.php(810): CodeIgniter\Router\RouteCollection->loadRoutes()
 2 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:40:11 --> ParseError: syntax error, unexpected token "(", expecting identifier or variable or "{" or "$"
in APPPATH\Config\Routes.php on line 13.
 1 SYSTEMPATH\CodeIgniter.php(810): CodeIgniter\Router\RouteCollection->loadRoutes()
 2 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:41:51 --> ParseError: syntax error, unexpected token "(", expecting identifier or variable or "{" or "$"
in APPPATH\Config\Routes.php on line 13.
 1 SYSTEMPATH\CodeIgniter.php(810): CodeIgniter\Router\RouteCollection->loadRoutes()
 2 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:42:24 --> ParseError: syntax error, unexpected token "(", expecting identifier or variable or "{" or "$"
in APPPATH\Config\Routes.php on line 13.
 1 SYSTEMPATH\CodeIgniter.php(810): CodeIgniter\Router\RouteCollection->loadRoutes()
 2 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 02:43:10 --> Error: Cannot call constructor
in APPPATH\Controllers\LaporController.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\LaporController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 04:32:59 --> ParseError: syntax error, unexpected variable "$routes", expecting "{"
in APPPATH\Config\Routes.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(810): CodeIgniter\Router\RouteCollection->loadRoutes()
 2 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 04:33:40 --> ParseError: syntax error, unexpected variable "$routes", expecting "{"
in APPPATH\Config\Routes.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(810): CodeIgniter\Router\RouteCollection->loadRoutes()
 2 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-20 04:33:41 --> ParseError: syntax error, unexpected variable "$routes", expecting "{"
in APPPATH\Config\Routes.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(810): CodeIgniter\Router\RouteCollection->loadRoutes()
 2 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-20 04:33:43 --> ParseError: syntax error, unexpected variable "$routes", expecting "{"
in APPPATH\Config\Routes.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(810): CodeIgniter\Router\RouteCollection->loadRoutes()
 2 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-20 04:33:49 --> ParseError: syntax error, unexpected variable "$routes", expecting "{"
in APPPATH\Config\Routes.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(810): CodeIgniter\Router\RouteCollection->loadRoutes()
 2 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 04:42:55 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "/lapor.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/lapor.php')
 2 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('/lapor', [], true)
 3 APPPATH\Controllers\HomeController.php(17): view('/lapor')
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\HomeController->lapor()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HomeController))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 07:35:13 --> ParseError: syntax error, unexpected token "return"
in APPPATH\Controllers\LaporController.php on line 54.
 1 SYSTEMPATH\Router\Router.php(515): CodeIgniter\Router\AutoRouter->getRoute('laporcontroller/save', 'post')
 2 SYSTEMPATH\Router\Router.php(211): CodeIgniter\Router\Router->autoRoute('laporcontroller/save')
 3 SYSTEMPATH\CodeIgniter.php(823): CodeIgniter\Router\Router->handle('laporcontroller/save')
 4 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 07:35:28 --> ParseError: syntax error, unexpected token "return"
in APPPATH\Controllers\LaporController.php on line 54.
 1 SYSTEMPATH\Router\Router.php(515): CodeIgniter\Router\AutoRouter->getRoute('laporcontroller/save', 'post')
 2 SYSTEMPATH\Router\Router.php(211): CodeIgniter\Router\Router->autoRoute('laporcontroller/save')
 3 SYSTEMPATH\CodeIgniter.php(823): CodeIgniter\Router\Router->handle('laporcontroller/save')
 4 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 07:36:17 --> ErrorException: Cannot declare class LaporModels because the name is already in use
in APPPATH\Models\LaporModels.php on line 6.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-03-20 07:37:04 --> ErrorException: Cannot declare class LaporModels because the name is already in use
in APPPATH\Models\LaporModels.php on line 6.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-03-20 07:37:40 --> ErrorException: Cannot declare class LaporModels because the name is already in use
in APPPATH\Models\LaporModels.php on line 6.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-03-20 07:37:58 --> Error: Class "App\Models\LaporModels" not found
in APPPATH\Controllers\LaporController.php on line 13.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\LaporController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 07:39:28 --> Error: Class "App\Models\LaporModels" not found
in APPPATH\Controllers\LaporController.php on line 14.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\LaporController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 07:40:33 --> Error: Class "App\Models\LaporModels" not found
in APPPATH\Controllers\LaporController.php on line 14.
 1 SYSTEMPATH\CodeIgniter.php(913): App\Controllers\LaporController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
ERROR - 2024-03-20 07:41:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_wbsystem', 3306, '', 0)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `da...', Array, false)
#4 C:\xampp\htdocs\wbs-ci\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\wbs-ci\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\wbs-ci\app\Controllers\LaporController.php(34): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\LaporController->save()
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
#10 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `da...', Array, false)
#3 C:\xampp\htdocs\wbs-ci\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\wbs-ci\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\wbs-ci\app\Controllers\LaporController.php(34): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\LaporController->save()
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2024-03-20 07:41:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `data` (`sifat_pelapor`, `firstName`, `noIdentitas`, `jk`, `alamat`, `email`, `phone`, `jenisPelanggaran`, `firstNameTerlapor`, `divisi`, `departemen`, `waktu`, `lokasi`, `kronologi`, `nominalKerugian`, `dokumen`) VALUES (:sifat_pelapor:, :firstName:, :noIdentitas:, :jk:, :alamat:, :email:, :phone:, :jenisPelanggaran:, :firstNameTerlapor:, :divisi:, :departemen:, :waktu:, :lokasi:, :kronologi:, :nominalKerugian:, :dokumen:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\LaporController.php(34): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LaporController->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
ERROR - 2024-03-20 07:43:09 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_wbsystem', 3306, '', 0)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `da...', Array, false)
#4 C:\xampp\htdocs\wbs-ci\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\wbs-ci\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\wbs-ci\app\Controllers\LaporController.php(34): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\LaporController->save()
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
#10 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `da...', Array, false)
#3 C:\xampp\htdocs\wbs-ci\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\wbs-ci\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\wbs-ci\app\Controllers\LaporController.php(34): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\LaporController->save()
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2024-03-20 07:43:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `data` (`sifat_pelapor`, `firstName`, `noIdentitas`, `jk`, `alamat`, `email`, `phone`, `jenisPelanggaran`, `firstNameTerlapor`, `divisi`, `departemen`, `waktu`, `lokasi`, `kronologi`, `nominalKerugian`, `dokumen`) VALUES (:sifat_pelapor:, :firstName:, :noIdentitas:, :jk:, :alamat:, :email:, :phone:, :jenisPelanggaran:, :firstNameTerlapor:, :divisi:, :departemen:, :waktu:, :lokasi:, :kronologi:, :nominalKerugian:, :dokumen:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\LaporController.php(34): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LaporController->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
ERROR - 2024-03-20 07:43:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_wbsystem', 3306, '', 0)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `da...', Array, false)
#4 C:\xampp\htdocs\wbs-ci\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\wbs-ci\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\wbs-ci\app\Controllers\LaporController.php(34): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\LaporController->save()
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
#10 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `da...', Array, false)
#3 C:\xampp\htdocs\wbs-ci\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\wbs-ci\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\wbs-ci\app\Controllers\LaporController.php(34): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\LaporController->save()
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2024-03-20 07:43:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `data` (`sifat_pelapor`, `firstName`, `noIdentitas`, `jk`, `alamat`, `email`, `phone`, `jenisPelanggaran`, `firstNameTerlapor`, `divisi`, `departemen`, `waktu`, `lokasi`, `kronologi`, `nominalKerugian`, `dokumen`) VALUES (:sifat_pelapor:, :firstName:, :noIdentitas:, :jk:, :alamat:, :email:, :phone:, :jenisPelanggaran:, :firstNameTerlapor:, :divisi:, :departemen:, :waktu:, :lokasi:, :kronologi:, :nominalKerugian:, :dokumen:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\LaporController.php(34): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LaporController->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
ERROR - 2024-03-20 07:43:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_wbsystem', 3306, '', 0)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `da...', Array, false)
#4 C:\xampp\htdocs\wbs-ci\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\wbs-ci\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\wbs-ci\app\Controllers\LaporController.php(34): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\LaporController->save()
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
#10 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `da...', Array, false)
#3 C:\xampp\htdocs\wbs-ci\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\wbs-ci\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\wbs-ci\app\Controllers\LaporController.php(34): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\LaporController->save()
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2024-03-20 07:43:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `data` (`sifat_pelapor`, `firstName`, `noIdentitas`, `jk`, `alamat`, `email`, `phone`, `jenisPelanggaran`, `firstNameTerlapor`, `divisi`, `departemen`, `waktu`, `lokasi`, `kronologi`, `nominalKerugian`, `dokumen`) VALUES (:sifat_pelapor:, :firstName:, :noIdentitas:, :jk:, :alamat:, :email:, :phone:, :jenisPelanggaran:, :firstNameTerlapor:, :divisi:, :departemen:, :waktu:, :lokasi:, :kronologi:, :nominalKerugian:, :dokumen:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\LaporController.php(34): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LaporController->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
ERROR - 2024-03-20 07:44:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_wbsystem', 3306, '', 0)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `da...', Array, false)
#4 C:\xampp\htdocs\wbs-ci\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\wbs-ci\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\wbs-ci\app\Controllers\LaporController.php(34): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\LaporController->save()
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
#10 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `da...', Array, false)
#3 C:\xampp\htdocs\wbs-ci\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\wbs-ci\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\wbs-ci\app\Controllers\LaporController.php(34): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\LaporController->save()
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2024-03-20 07:44:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `data` (`sifat_pelapor`, `firstName`, `noIdentitas`, `jk`, `alamat`, `email`, `phone`, `jenisPelanggaran`, `firstNameTerlapor`, `divisi`, `departemen`, `waktu`, `lokasi`, `kronologi`, `nominalKerugian`, `dokumen`) VALUES (:sifat_pelapor:, :firstName:, :noIdentitas:, :jk:, :alamat:, :email:, :phone:, :jenisPelanggaran:, :firstNameTerlapor:, :divisi:, :departemen:, :waktu:, :lokasi:, :kronologi:, :nominalKerugian:, :dokumen:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\LaporController.php(34): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LaporController->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
ERROR - 2024-03-20 07:47:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_wbsystem', 3306, '', 0)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `da...', Array, false)
#4 C:\xampp\htdocs\wbs-ci\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\wbs-ci\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\wbs-ci\app\Controllers\LaporController.php(34): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\LaporController->save()
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
#10 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `da...', Array, false)
#3 C:\xampp\htdocs\wbs-ci\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\wbs-ci\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp\htdocs\wbs-ci\app\Controllers\LaporController.php(34): CodeIgniter\Model->insert(Array)
#7 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\LaporController->save()
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2024-03-20 07:47:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `data` (`sifat_pelapor`, `firstName`, `noIdentitas`, `jk`, `alamat`, `email`, `phone`, `jenisPelanggaran`, `firstNameTerlapor`, `divisi`, `departemen`, `waktu`, `lokasi`, `kronologi`, `nominalKerugian`, `dokumen`) VALUES (:sifat_pelapor:, :firstName:, :noIdentitas:, :jk:, :alamat:, :email:, :phone:, :jenisPelanggaran:, :firstNameTerlapor:, :divisi:, :departemen:, :waktu:, :lokasi:, :kronologi:, :nominalKerugian:, :dokumen:)', [...], false)
 3 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\LaporController.php(34): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LaporController->save()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 07:47:32 --> Error: Class "CI_Model" not found
in APPPATH\Models\HomeModels.php on line 2.
 1 SYSTEMPATH\Autoloader\Autoloader.php(311): include_once()
 2 SYSTEMPATH\Autoloader\Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\wbs-ci\\app\\Models\\HomeModels.php')
 3 SYSTEMPATH\Autoloader\Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\HomeModels')
 4 APPPATH\Controllers\TestController.php(12): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\HomeModels')
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\TestController->testDatabaseConnection()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 07:49:01 --> CodeIgniter\Database\Exceptions\DatabaseException: You must set the database table to be used with your query.
in SYSTEMPATH\Database\BaseConnection.php on line 884.
 1 SYSTEMPATH\Model.php(662): CodeIgniter\Database\BaseConnection->table(null)
 2 SYSTEMPATH\Model.php(235): CodeIgniter\Model->builder()
 3 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestController.php(13): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\TestController->testDatabaseConnection()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 07:50:41 --> Error: Class "App\Controllers\LaporModels" not found
in APPPATH\Controllers\TestController.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\TestController->testDatabaseConnection()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestController))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
ERROR - 2024-03-20 07:51:03 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_wbsystem', 3306, '', 0)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\wbs-ci\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\wbs-ci\app\Controllers\TestController.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\TestController->testDatabaseConnection()
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestController))
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\wbs-ci\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\wbs-ci\app\Controllers\TestController.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\TestController->testDatabaseConnection()
#7 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestController))
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2024-03-20 07:51:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `data`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TestController.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\TestController->testDatabaseConnection()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
ERROR - 2024-03-20 07:52:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_wbsystem', 3306, '', 0)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\wbs-ci\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\wbs-ci\app\Controllers\TestController.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\TestController->testDatabaseConnection()
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestController))
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\wbs-ci\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\wbs-ci\app\Controllers\TestController.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\TestController->testDatabaseConnection()
#7 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestController))
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2024-03-20 07:52:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `data`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TestController.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\TestController->testDatabaseConnection()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
ERROR - 2024-03-20 07:53:57 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db_wbsystem', 3306, '', 0)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\wbs-ci\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\wbs-ci\app\Controllers\TestController.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\TestController->testDatabaseConnection()
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestController))
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\wbs-ci\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\wbs-ci\app\Controllers\TestController.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\TestController->testDatabaseConnection()
#7 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestController))
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2024-03-20 07:53:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `data`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\TestController.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\TestController->testDatabaseConnection()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
ERROR - 2024-03-20 07:56:38 --> mysqli_sql_exception: Column 'dokumen' cannot be null in C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\wbs-ci\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `da...', 0)
#1 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `da...')
#2 C:\xampp\htdocs\wbs-ci\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `da...')
#3 C:\xampp\htdocs\wbs-ci\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `da...', Array, false)
#4 C:\xampp\htdocs\wbs-ci\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\wbs-ci\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\wbs-ci\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\wbs-ci\app\Controllers\LaporController.php(34): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(941): App\Controllers\LaporController->save()
#9 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
#10 C:\xampp\htdocs\wbs-ci\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\wbs-ci\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\wbs-ci\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-20 07:56:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'dokumen' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `data` (`sifat_pelapor`, `firstName`, `noIdentitas`, `jk`, `alamat`, `email`, `phone`, `jenisPelanggaran`, `firstNameTerlapor`, `divisi`, `departemen`, `waktu`, `lokasi`, `kronologi`, `nominalKerugian`, `dokumen`) VALUES (:sifat_pelapor:, :firstName:, :noIdentitas:, :jk:, :alamat:, :email:, :phone:, :jenisPelanggaran:, :firstNameTerlapor:, :divisi:, :departemen:, :waktu:, :lokasi:, :kronologi:, :nominalKerugian:, :dokumen:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\LaporController.php(34): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LaporController->save()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 07:56:38 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'dokumen' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `data` (`sifat_pelapor`, `firstName`, `noIdentitas`, `jk`, `alamat`, `email`, `phone`, `jenisPelanggaran`, `firstNameTerlapor`, `divisi`, `departemen`, `waktu`, `lokasi`, `kronologi`, `nominalKerugian`, `dokumen`) VALUES (\'1\', \'n n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n\', NULL)')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `data` (`sifat_pelapor`, `firstName`, `noIdentitas`, `jk`, `alamat`, `email`, `phone`, `jenisPelanggaran`, `firstNameTerlapor`, `divisi`, `departemen`, `waktu`, `lokasi`, `kronologi`, `nominalKerugian`, `dokumen`) VALUES (\'1\', \'n n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n\', NULL)')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `data` (`sifat_pelapor`, `firstName`, `noIdentitas`, `jk`, `alamat`, `email`, `phone`, `jenisPelanggaran`, `firstNameTerlapor`, `divisi`, `departemen`, `waktu`, `lokasi`, `kronologi`, `nominalKerugian`, `dokumen`) VALUES (:sifat_pelapor:, :firstName:, :noIdentitas:, :jk:, :alamat:, :email:, :phone:, :jenisPelanggaran:, :firstNameTerlapor:, :divisi:, :departemen:, :waktu:, :lokasi:, :kronologi:, :nominalKerugian:, :dokumen:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\LaporController.php(34): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LaporController->save()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 07:56:38 --> [Caused by] mysqli_sql_exception: Column 'dokumen' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `data` (`sifat_pelapor`, `firstName`, `noIdentitas`, `jk`, `alamat`, `email`, `phone`, `jenisPelanggaran`, `firstNameTerlapor`, `divisi`, `departemen`, `waktu`, `lokasi`, `kronologi`, `nominalKerugian`, `dokumen`) VALUES (\'1\', \'n n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n\', NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `data` (`sifat_pelapor`, `firstName`, `noIdentitas`, `jk`, `alamat`, `email`, `phone`, `jenisPelanggaran`, `firstNameTerlapor`, `divisi`, `departemen`, `waktu`, `lokasi`, `kronologi`, `nominalKerugian`, `dokumen`) VALUES (\'1\', \'n n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n\', NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `data` (`sifat_pelapor`, `firstName`, `noIdentitas`, `jk`, `alamat`, `email`, `phone`, `jenisPelanggaran`, `firstNameTerlapor`, `divisi`, `departemen`, `waktu`, `lokasi`, `kronologi`, `nominalKerugian`, `dokumen`) VALUES (\'1\', \'n n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n n\', \'n\', \'n\', \'n\', \'n\', \'n\', \'n\', NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `data` (`sifat_pelapor`, `firstName`, `noIdentitas`, `jk`, `alamat`, `email`, `phone`, `jenisPelanggaran`, `firstNameTerlapor`, `divisi`, `departemen`, `waktu`, `lokasi`, `kronologi`, `nominalKerugian`, `dokumen`) VALUES (:sifat_pelapor:, :firstName:, :noIdentitas:, :jk:, :alamat:, :email:, :phone:, :jenisPelanggaran:, :firstNameTerlapor:, :divisi:, :departemen:, :waktu:, :lokasi:, :kronologi:, :nominalKerugian:, :dokumen:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\LaporController.php(34): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LaporController->save()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 08:00:12 --> ParseError: Unclosed '{' on line 9
in APPPATH\Controllers\LaporController.php on line 67.
 1 SYSTEMPATH\Router\Router.php(515): CodeIgniter\Router\AutoRouter->getRoute('laporcontroller/save', 'post')
 2 SYSTEMPATH\Router\Router.php(211): CodeIgniter\Router\Router->autoRoute('laporcontroller/save')
 3 SYSTEMPATH\CodeIgniter.php(823): CodeIgniter\Router\Router->handle('laporcontroller/save')
 4 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 08:00:35 --> Error: Call to a member function isValid() on null
in APPPATH\Controllers\LaporController.php on line 37.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LaporController->save()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
INFO - 2024-03-20 08:02:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-20 08:03:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-20 08:06:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-03-20 08:25:21 --> ParseError: syntax error, unexpected token "=>"
in APPPATH\Controllers\LaporController.php on line 54.
 1 SYSTEMPATH\Router\Router.php(515): CodeIgniter\Router\AutoRouter->getRoute('laporcontroller/save', 'post')
 2 SYSTEMPATH\Router\Router.php(211): CodeIgniter\Router\Router->autoRoute('laporcontroller/save')
 3 SYSTEMPATH\CodeIgniter.php(823): CodeIgniter\Router\Router->handle('laporcontroller/save')
 4 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 08:25:32 --> ParseError: syntax error, unexpected token "else", expecting "function" or "const"
in APPPATH\Controllers\LaporController.php on line 57.
 1 SYSTEMPATH\Router\Router.php(515): CodeIgniter\Router\AutoRouter->getRoute('laporcontroller/save', 'post')
 2 SYSTEMPATH\Router\Router.php(211): CodeIgniter\Router\Router->autoRoute('laporcontroller/save')
 3 SYSTEMPATH\CodeIgniter.php(823): CodeIgniter\Router\Router->handle('laporcontroller/save')
 4 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
INFO - 2024-03-20 08:37:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-20 08:42:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2024-03-20 08:45:53 --> Error: Call to a member function isValid() on array
in APPPATH\Controllers\LaporController.php on line 39.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LaporController->save()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 08:46:36 --> Error: Call to a member function isValid() on array
in APPPATH\Controllers\LaporController.php on line 39.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LaporController->save()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 08:47:55 --> Error: Call to a member function isValid() on array
in APPPATH\Controllers\LaporController.php on line 40.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LaporController->save()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 09:01:59 --> Error: Call to a member function isValid() on array
in APPPATH\Controllers\LaporController.php on line 37.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\LaporController->save()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LaporController))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 09:04:02 --> ParseError: syntax error, unexpected token "return", expecting "function" or "const"
in APPPATH\Controllers\LaporController.php on line 70.
 1 SYSTEMPATH\Router\Router.php(515): CodeIgniter\Router\AutoRouter->getRoute('laporcontroller/save', 'post')
 2 SYSTEMPATH\Router\Router.php(211): CodeIgniter\Router\Router->autoRoute('laporcontroller/save')
 3 SYSTEMPATH\CodeIgniter.php(823): CodeIgniter\Router\Router->handle('laporcontroller/save')
 4 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
CRITICAL - 2024-03-20 09:04:56 --> ParseError: Unclosed '{' on line 9
in APPPATH\Controllers\LaporController.php on line 72.
 1 SYSTEMPATH\Router\Router.php(515): CodeIgniter\Router\AutoRouter->getRoute('laporcontroller/save', 'post')
 2 SYSTEMPATH\Router\Router.php(211): CodeIgniter\Router\Router->autoRoute('laporcontroller/save')
 3 SYSTEMPATH\CodeIgniter.php(823): CodeIgniter\Router\Router->handle('laporcontroller/save')
 4 SYSTEMPATH\CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\wbs-ci\\public\\index.php')
INFO - 2024-03-20 09:05:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
